# Generated by Django 2.1.7 on 2019-05-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='data_piblicacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='descricao',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Descriçaõ'),
        ),
    ]
