# Generated by Django 2.1.7 on 2019-05-12 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_auto_20190512_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='data_piblicacao',
            new_name='data_publicacao',
        ),
    ]
