# Generated by Django 2.1.7 on 2019-05-12 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_auto_20190512_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
