# Generated by Django 2.1.7 on 2019-05-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_auto_20190512_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='status',
        ),
        migrations.AddField(
            model_name='posts',
            name='publicado',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
