# Generated by Django 2.1.7 on 2019-05-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0009_auto_20190526_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
